name = "psynex-exam"
main = "src/index.ts"
compatibility_date = "2025-07-18"
workers_dev = true

[[kv_namespaces]]
binding = "TAXO"
id = "d37f216a7880402baecb0ea71e3b189b"   # همینی که خودت داری

[[kv_namespaces]]
binding = "DATA"
id = "4e7f07f4153214fd818cd00e53a18b7"    # همینی که خودت داری

